feat: Update build configuration and dependencies
This commit updates the project's build configuration to use Gradle 8.5 and Kotlin 1.9.22. It also adjusts the application namespace and root project name for consistency. Additionally, several new dependencies have been added to improve core functionality, including Kotlin extensions, Material Design, ConstraintLayout, splash screen support, and Navigation components. The Java version is also updated to 17.

diff --git a/.github/workflows/android_build.yml b/.github/workflows/android_build.yml
--- a/.github/workflows/android_build.yml
+++ b/.github/workflows/android_build.yml
@@ -19,8 +19,16 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
+      - name: List Files Debug
+        run: |
+          pwd
+          ls -F
+          [ -f settings.gradle ] && echo "settings.gradle found" || echo "settings.gradle NOT found"
+
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
+        with:
+          gradle-version: '8.5'
 
       - name: Build APK
         run: gradle assembleDebug --stacktrace
